#!/bin/sh
set -e

BASENAME=$(basename $0)
DIRNAME=$(dirname $0)

echo "初回起動時には、自動でインストールプログラムが実行します。"
echo "gh extension を実行すると、インストールプログラム兼mainプログラムの ${BASENAME} が実行されます。"
echo "- gh-activity      : シェルスクリプトで記述されたインストールプログラム兼mainプログラム"
echo "${BASENAME} は、シェルスプリプトで、インストールされるプログラムは、以下のプログラムです。"
echo "- gh-activity-c    : C言語で作成されたプログラム"
echo "- gh-activity-cpp  : C++言語で作成されたプログラム"
echo "- gh-activity-rust : Rust言語で作成されたプログラム"
echo "- gh-activity-sh   : Shell言語で作成されたプログラム"

echo "インストールは、アセットから、ダウンロードして、インストールします。"
echo "インストール先は、ホームディレクトリのgh-activityにインストールされます。"
echo "インストールされたプログラムは、gh activity経由で実行されます。"
echo "- gh activity c    : gh-activity-cを実行"
echo "- gh activity cpp  : gh-activity-cppを実行"
echo "- gh activity rust : gh-activity-rustを実行"
echo "- gh activity sh   : gh-activity-shを実行"

echo "--------------------------------------"

echo gh extensionが自動生成すると思われる、manifest.yml ファイル
echo バージョン情報を取得できるので、バージョンコントールできます。
echo "${DIRNAME}/manifest.yml を表示します。"
cat ${DIRNAME}/manifest.yml

echo "--------------------------------------"
echo "uname -s で、OS情報を表示します。"
echo "linux : Linux"
echo "windos : ???"
echo "mac : ???"
echo "--------------------------------------"
uname -s
echo "--------------------------------------"
echo "uname -m で、アーキテクチャ情報を表示します。"
echo "wSL2 : x86_64"
echo "mac : ???"
echo "windows : ???"
echo "--------------------------------------"
uname -m

echo "--------------------------------------"
echo "uname -i で、ハードウェア情報を表示します。"
echo "WSL2 : x86_64"
echo "windows : ???"
echo "--------------------------------------"
uname -i

echo DIRNAME=${DIRNAME}
# ex: 1.0.0
VERSION=$(cat ${DIRNAME}/manifest.yml | grep "tag" | awk '{print $2}')
# ex: linux-amd64
ARTIFACT="linux-amd64"

ASSET_URL="https://github.com/kouji-sasaya/gh-activity/releases/download/${VERSION}/gh-activity_${VERSION}_${ARTIFACT}.tar.gz"

curl --silent -L "${ASSET_URL}" -o "${DIRNAME}/gh-activity.tar.gz"

cd ${DIRNAME}
tar xf gh-activity.tar.gz
cd -

if [ "${1}" = "c" ]; then
  ${DIRNAME}/bin/gh-activity-c $@
  exit
fi