name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    name: Release binary for multi OS
    strategy:
      matrix:
        include:
          # 64-bit macOS
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: x86_64-apple-darwin
          # 64-bit MinGW
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            artifact: x86_64-pc-windows-gnu.exe
          # 64-bit MSVC
          - os: ubuntu-latest
            target: x86_64-pc-windows-msvc
            artifact: x86_64-pc-windows-msvc.exe
          # 64-bit Linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: x86_64-unknown-linux-gnu
          # ARM64 Linux
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact: aarch64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target $${{ matrix.target }}

      - uses: cli/gh-extension-precompile@v1
        with:
          build_script_override: "script/build.sh"
        env:
          TARGET: ${{ matrix.target }}
          ARTIFACT: ${{ matrix.artifact }}
