name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    name: Release binary for multi OS
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: darwin-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact: darwin-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: windows-amd64.exe
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            artifact: windows-arm64.exe
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: linux-amd64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact: linux-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - uses: cli/gh-extension-precompile@v1
        with:
          build_script_override: "script/build.sh"
        env:
          TARGET: ${{ matrix.target }}
          ARTIFACT: ${{ matrix.artifact }}
